### ISSUE TITLE
Add hover effect to message button

### ISSUE THREAD

**Issue by Akshitha2106** [jineshnagori/hacktoberfest2022-WebDev#122]
![2022-10-18 (1)](https://user-images.githubusercontent.com/101176297/196496016-9a48444e-3c80-4791-bf44-12d50ac28d53.png)
Respected sir(@jonmichael69 ) please assign me this issue

**Comment by Akshitha2106** [comment]
Respected sir (@jonmichael69 ) please assign me this issue under hacktoberfest.

**Comment by gitamandeep** [comment]
please assign this issue to me i want to work on this issue

**Comment by Hiresh007** [comment]
please assign if no on working

**Comment by laveshverma007** [comment]
Please assign it to me under hacktoberfest
