### ISSUE TITLE
Darkmode in different pages

### ISSUE THREAD

**Issue by asmitsirohi** [jineshnagori/hacktoberfest2022-WebDev#133]
On some of the pages, there is no facility for dark mode. The list is as follows.

* About page
* Signup Page
* Login Page

Also, there is a requirement for a feature that will keep track that if dark mode is enabled on one page. So it will automatically be enabled for the whole website.

**Comment by asmitsirohi** [comment]
Please, assign this issue to me.

**Comment by Manishgupta200** [comment]
Can i solve this issue. Assign it to me

**Comment by Manishgupta200** [comment]
Thanks for assigning
