### ISSUE TITLE
Adding hover effect

### ISSUE THREAD

**Issue by AditiSingh2003** [jineshnagori/hacktoberfest2022-WebDev#182]
Adding hover effect to the text

![Screenshot (76)](https://user-images.githubusercontent.com/97729662/198836867-5ed33f99-2673-4d04-a388-7f09892ee6cd.png)

**Comment by CraigP17** [comment]
I can do this, do you want just the text (Lorem Epsom) to hover, or the entire text including author and read time, or include the image to hover?

**Comment by CraigP17** [comment]
@jineshnagori why was this marked as complete? I can quickly finish this for hacktoberfest
